name: CI Pipeline

on:
  push:
    branches: [ main, noopur_task ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip

    - name: Run script
      run: |
        python file.txt || echo "This is a text file, skipping execution"

    - name: Success message
      run: echo "CI pipeline executed successfully!"