name: Python Automation

on:
  push:
    branches:
      - main
      - Ayush

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check Python Version
        run: python --version

      - name: Run Python Program
        run: python Ay.py