name: Git Automation Workflow

on:
  push:
    branches:
      - main
      - Ayush

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Display Python Version
        run: python --version

      - name: Run Python File
        run: python Ay.py

      - name: Workflow Completed
        run: echo "Automation Successful"